target-name: bugs.yaml
data-root:
  files:
    var/log/neutron/neutron-server.log: |
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event [-] Unexpected exception in notify_loop: FileNotFoundError: [Errno 2] No such file or directory: 'ovsdb-client'
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event Traceback (most recent call last):
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event   File "/usr/lib/python3/dist-packages/ovsdbapp/event.py", line 143, in notify_loop
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event     match.run(event, row, updates)
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event   File "/usr/lib/python3/dist-packages/neutron/plugins/ml2/drivers/ovn/mech_driver/ovsdb/ovsdb_monitor.py", line 434, in run
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event     self.driver.delete_mac_binding_entries(row.external_ip)
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event   File "/usr/lib/python3/dist-packages/neutron/plugins/ml2/drivers/ovn/mech_driver/mech_driver.py", line 1068, in delete_mac_binding_entries
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event     return processutils.execute(*cmd,
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event   File "/usr/lib/python3/dist-packages/oslo_concurrency/processutils.py", line 383, in execute
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event     obj = subprocess.Popen(cmd,
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event   File "/usr/lib/python3/dist-packages/eventlet/green/subprocess.py", line 58, in __init__
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event     subprocess_orig.Popen.__init__(self, args, 0, *argss, **kwds)
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event   File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event     self._execute_child(args, executable, preexec_fn, close_fds,
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event   File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event     raise child_exception_type(errno_num, err_msg, err_filename)
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event FileNotFoundError: [Errno 2] No such file or directory: 'ovsdb-client'
      2022-02-05 15:08:46.198 75085 ERROR ovsdbapp.event
  copy-from-original:
    - sos_commands/date/date
    - uptime
raised-bugs:
  https://bugs.launchpad.net/bugs/1960319: >-
    neutron-server is reporting that ovsdb-client is not installed so is unable
    to perform some tasks. This is because package 'openvswitch-common' is
    missing. To workaround the problem you can manually install this package.
